### ISSUE TITLE
ヘッダーとフッターを記載したレイアウトblogが読み込まれていない

### ISSUE THREAD

**Issue by gel1123** [azain4645/nuxt3-blog#1]
## 事象
`layouts/blog.vue` に下記のレイアウトコンポーネントを定義したが、アプリケーションにこのレイアウトが読み込まれない

```
<template>
  <div>
    <header class="text-white bg-green-500 p-4">HEADER</header>
    <slot />
    <footer class="text-white bg-green-500 p-4">FOOTER</footer>
  </div>
</template>
```

## 結論

`app.vue` を下記のように修正すると、アプリにレイアウトが反映されます！

```diff
 <template>
   <div>
+    <NuxtLayout name="blog">
        <NuxtPage/>
+    </NuxtLayout>
   </div>
 </template>
```

<img width="566" alt="スクリーンショット 2022-07-13 22 28 24" src="https://user-images.githubusercontent.com/41170561/178745202-61580d24-f5cb-4864-ab4b-b5d288ac6192.png">

## もう少し詳しく
layoutsディレクトリ内のコンポーネントはアプリケーションに組み込めるレイアウトとしてNuxt3に自動登録されますが、実際にレイアウトをアプリに反映させるなら、 `app.vue` に `NuxtLayout` タグを挿入する必要があります。

この際、NuxtLayoutのname属性に指定した値が、実際に `layouts`ディレクトリに配置したvueファイル名に対応するようになっています。

なお、name属性を書かない場合には、自動で `layouts/default.vue` をレイアウトとして画面に表示します。（その際、 `layouts/default.vue` が存在しないと、画面にはレイアウトが適用されません）

## 参考ドキュメント
https://v3.nuxtjs.org/guide/directory-structure/layouts/

**Comment by azain4645** [comment]
詳しく教えて頂き、ありがとうございます！
確かにドキュメントみるのが一番良さそうですね

デフォルトは、layouts/default.vue
app.vue のNuxtLayoutにnameをつける
もしくは、page側に
<script>
  definePageMeta({
    layout: 'blog'
  });
</script>
に記載すれば適応されるということで理解しました
