### ISSUE TITLE
pageの書き方、コンポーネントの考え方について

### ISSUE THREAD

**Issue by azain4645** [azain4645/nuxt3-blog#2]
もう少し雰囲気を掴みたいので、次はおみくじのページを作っています。

質問としては、Nuxt2では以下のような書き方のサンプルを見ましたが、Nuxt3においても実装として正しいのか
scriptの中にexport defaultとおいて、中にデータや計算を書くということについてです。

もう一つは、基本的にはコンポーネントを作って組み上げていくような話を聞きますが、全てコンポーネントで組むとか、使い回す可能性がある部分だけコンポーネントを作るとか開発のイメージがあれば教えてください。

https://github.com/azain4645/nuxt3-blog/blob/64e3910ff06f5bc405bcb5f72ce9ee3e5fae6f84/pages/fortune.vue#L1-L25

**Comment by gel1123** [comment]
@azain4645 

> 質問としては、Nuxt2では以下のような書き方のサンプルを見ましたが、Nuxt3においても実装として正しいのか
> scriptの中にexport defaultとおいて、中にデータや計算を書くということについてです。

これはNuxt2が標準とするVue2での書き方でして、Vue2自体がじきにサポート対象外となることから、（今後も書くことはできるものの）お勧めしない書き方ですね！

Nuxt3は現在のVueのメインストリームであるVue3をベースにしており、「script setup」という上記がだいぶシンプルになった記法で書いていきます！

ざっくり同じコードを書くならこんな感じです（このIssue上での走り書きなので、もしかすると一部誤りがあるかもですが）

```vue
<script setup lang="ts">
const lucky = ref("");
const fortuneTest = () => {
  lucky.value = "ランダムな結果を渡す"
}
</script>
<template>
  <!-- template内は同じなので割愛 -->
</template>
```

**Comment by gel1123** [comment]
@azain4645 

> もう一つは、基本的にはコンポーネントを作って組み上げていくような話を聞きますが、全てコンポーネントで組むとか、使い回す可能性がある部分だけコンポーネントを作るとか開発のイメージがあれば教えてください。

そうですね。フロントエンドのビューにあたる部分はすべてコンポーネント（xxxx.vueファイル）として作成していきますね！
ReactやVueでは、MVCではなく「MVVM（Model, View, ViewModel）」という考え方が一般的でして、これはざっくり言うなら「モデルって実質的にフロントエンドのUIに依存するから、View と Model 一緒にしていいよね！（ViewModel）」と言う考え方です。

ですので、ある程度のロジックなら script setup 内にコード分離させないまま書くのですが、流石に長くなったり使い回すような業務ロジックであれば、serviceやusecaseなどアプリケーションロジック / ユーザ目線の操作 などの粒度で tsファイルとして分割し、それを xxx.vue 内にimportして使うケースが多いです！

※例えばデータベースとの接続コードなどは、都度 vueファイルの script setup として書いていくと冗長なので、それらをまとめた repository 用のディレクトリにコード分割しますね！

**Comment by azain4645** [comment]
詳しく説明いただきありがとうございます！
とりあえず下記のコードに書き換えて動きました。

```
<script setup lang="ts">
  const lucky = ref("");
  const results = ['大吉', '吉', '大凶'];
  const fortuneTest = () => {
    const random = Math.floor( Math.random() * 3);
    lucky.value = results[random];
  }
</script>
```

`const lucky = ref("");`
については、単に初期化する時にこういう書き方をするという理解で問題ないですか？

あと、setupについて理解ができていないのですが、もう少し説明いただいてもよろしいですか？

**Comment by gel1123** [comment]
@azain4645 
お、いいですね！
`const lucky = ref("")` は「状態」としてUIと協調して動作する特別な変数です！
`ref` メソッドが、この「状態」を作成するメソッドになっていまして、ここでは初期値を空の文字列にしている次第です。

refで「状態」として定義された変数は、その値を変えた時に、状態を組み込んだテンプレートが再度レンダリングされて、画面に表示される値が変わるようになっています！

> あと、setupについて理解ができていないのですが、もう少し説明いただいてもよろしいですか？

承知しました！
Vueって元々、このIssueの最初にazain4645さんが書いてくださったような書き方で動くものだったんですね。ですがこれではあまりにも書きづらい、可読性が悪いということで、「元々のVueの書き方」の糖衣構文として作られたのが script setup です！

この script setup にも `<script setup>` とスクリプトタグに書くのではなく、スクリプトタグの中に色々と書いていくバージョンがあったのですが、現在では `<script setup>` の記法が一般的になっています！

※公式の解説ページも貼っておきますね！
https://v3.ja.vuejs.org/api/sfc-script-setup.html

**Comment by gel1123** [comment]
補足です！

> refで「状態」として定義された変数は、その値を変えた時に、状態を組み込んだテンプレートが再度レンダリングされて、画面に表示される値が変わるようになっています！

これですが、逆に ref を使った「状態」ではなく単なる値を変数に入れてテンプレートに組み込んだ場合には、その値が画面表示後に変更されたとしても、テンプレートは再度描画されないようになっています！

* 「状態」として動的にUIと連動したい変数はrefで定義する
* 動的な連動が不要なら、単なる値をテンプレートに組み込む

ざっくりこんな感じの使い分けになりますね！

**Comment by azain4645** [comment]
> これですが、逆に ref を使った「状態」ではなく単なる値を変数に入れてテンプレートに組み込んだ場合には、その値が画面表示後に変更されたとしても、テンプレートは再度描画されないようになっています！

確かに試して、constからletに変えて、lucky = で書き換えようとしても反映されませんね！
refについては理解できました。
