### ISSUE TITLE
配列の要素がバインディングされない

### ISSUE THREAD

**Issue by azain4645** [azain4645/nuxt3-blog#3]
次にtodoページを作成しています。

初期値のtodosは表示されましたが、追加の内容が表示されません。
先ほどのrefの問題かと思いますが（データ上は追加されているため）

こういった配列などの要素をバインディングする場合はどのように書いたら良いでしょうか

https://github.com/azain4645/nuxt3-blog/blob/9b1d2685d67edb6821f18dad60b6c3c95c5658de/pages/todoList.vue#L2-L14

**Comment by gel1123** [comment]
@azain4645 
配列に関しても同じようにrefで扱うことができます！
今回の場合ですと、このような形で ref による状態定義が可能です！

```diff
 <script setup lang="ts">
-  const todos = [
+  const todos = ref([
         {content: 'テスト', created: '2020-04-30 17:00', state: '作業前'}, 
         {content: 'コーディング', created: '2020-04-30 16:00', state: '作業中'},
         {content: '環境構築', created: '2020-04-30 15:30', state: '完了'}
-      ]
+      ])
 
   const addTodo = () => {
-    todos.push({
+    todos.value.push({
       content: "追加テスト",
       created: "2020-04-30 12:30",
       state: '作業前'
```

**Comment by azain4645** [comment]
ありがとうございます。ref([])で動作することを確認しました。
ネットで他調べていたら reactive というので定義する書き方もあるようでしたが、使い分けとかどちらの方がとかありますか？

あと、Todo型書いてみました😀

```
  interface Todo {
    content: string;
    created: string;
    state: boolean;
  }
 
  let todos = reactive<Todo[]>([
        {content: 'テスト', created: '2020-04-30 17:00', state: false}, 
        {content: 'コーディング', created: '2020-04-30 16:00', state: false},
        {content: '環境構築', created: '2020-04-30 15:30', state: true}
      ])

  const addTodo = () => {
    todos.push({
      content: "追加テスト",
      created: "2020-04-30 12:30",
      state: false
    })
  }
```

**Comment by azain4645** [comment]
stateについては、booleanでtrue,falseを持たせる形にしようと思います。

表示の方は、falseなら着手前、trueなら完了後と表示させたいですが、どのように書きますか？
0 着手前 1 実施中 2完了　のケースも合わせて教えていただけたと思います
<td class="">{{ item.state }}</td>

**Comment by gel1123** [comment]
@azain4645 

> ネットで他調べていたら reactive というので定義する書き方もあるようでしたが、使い分けとかどちらの方がとかありますか？

巨大なオブジェクトをひとまとめに状態として扱いたい時にはreactiveを使い、そうでない限りは基本的にrefを使うというのが、ざっくりとした使い分けですね！

このあたりは個人やチームの匙加減によるところかもしれませんが、極力refで困らない範囲はrefで片付ける派が多いですね！（むしろreactive使うな派もいます）

ref vs reactive についてはこの記事なんかが詳しいです。
https://zenn.dev/azukiazusa/articles/ref-vs-article

> あと、Todo型書いてみました😀

いいですね！　ちなみにTypeScript界隈では interface派 vs type派 に分かれていまして、これもまた双方「必ずこっちがいい」と言うものはなかったりします。

私の身の回りではtype派揃いだったりしますが、あえて class + implements xxxInterface させたい時には、interfaceも使いますね！
（とはいえ、私はtsではそもそもあまりclassを書きたくない派なので、その機会はあまり無かったりもしますが）

https://zenn.dev/seya/articles/aa94166c977280

> 表示の方は、falseなら着手前、trueなら完了後と表示させたいですが、どのように書きますか？

Vueのテンプレートには v-if という値に応じて出力するテンプレートを切り替える機能がありますので、v-if, v-else を使えば実現できます！

https://jp.vuejs.org/v2/guide/conditional.html

> 0 着手前 1 実施中 2完了　のケースも合わせて教えていただけたと思います

booleanだと２値しかないので、３パターンのケースならフラグとして適当な値を状態に持たせるか、あるいはいっそテンプレートに表示する文字列自体を状態として持たせるかのどちらかがいいですね！

**Comment by azain4645** [comment]
ありがとうございます。書き方の派閥が色々あるんですね。。
とりあえず、詳しいことが自分で理解できるまでは、typeとrefを基本的に使って進めたいと思います。

refで型を指定する書き方がわからなかったので教えていただいてよろしいでしょうか？
まぁこの場合、型推論で定義されるので必要ではないかもしれませんが。

```
  type Todo = {
    content: string;
    created: string;
    state: boolean;
  }
 
  const todos = ref([
         {content: 'テスト', created: '2020-04-30 17:00', state: true}, 
         {content: 'コーディング', created: '2020-04-30 16:00', state: true},
         {content: '環境構築', created: '2020-04-30 15:30', state: false}
      ])
```

**Comment by gel1123** [comment]
@azain4645 

> 書き方の派閥が色々あるんですね。。

そうですね...このあたり年月と共にどれが優勢かが変わってくる部分でもあるでもあります。
（昔はinterface優勢でしたが、typeが段々機能的に充実してきたので最近はtypeに....って感じだったりですね）

もちろん、そういった経緯で「必ずどっちが」という話でもないので、azain4645さんが書きたければ、どんどん色んな書き方試してもらって大丈夫ですよ！！

> refで型を指定する書き方がわからなかったので教えていただいてよろしいでしょうか？

承知しました！
refもここはreactiveと同様にジェネリクス使うことができまして、ほぼ同じ書き方でいけます！

```diff
-  const todos = ref([
+  const todos = ref<Todo[]>([
         {content: 'テスト', created: '2020-04-30 17:00', state: true}, 
         {content: 'コーディング', created: '2020-04-30 16:00', state: true},
         {content: '環境構築', created: '2020-04-30 15:30', state: false}
])
```
