### ISSUE TITLE
SSGモードでビルドした後に、生成された資材でアプリケーションを開く方法

### ISSUE THREAD

**Issue by gel1123** [azain4645/nuxt3-blog#6]
@azain4645 
SSGとしてビルドした Nuxt3 アプリケーションは、下記の手順で開くことができます！

## 手順1. nuxt.config.tsのセットアップ

```typescript
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ["@/assets/css/styles.css"],
  build: {
    postcss: {
      postcssOptions: require("./postcss.config.js"),
    },
  },
  ssr: false,

  // もしSSGではなく、特定のプラットフォーム向けのSSRデプロイセットでビルドしたいなら
  // 参考：https://nitro.unjs.io/deploy/
  // nitro: {
  //   preset: "aws-lambda" // AWS Lambda + S3 で Nuxt3 SSR を動作させるプリセット
  // }
})

```

## 手順2. yarn generate する
ここはやってもらった通りなので割愛。

## 手順3. 生成された資材を実際にWebホスティングで開けるか確認する
node.js でやるなら一番手っ取り早いのがこれです

```
# nuxt3-blogディレクトリ直下で実行するならこう
#
# ※ちなみに npx は npmに公開されたパッケージをローカルにインストールしないまま利用するためのコマンドです
#（今回なら serveパッケージをその場でダウンロードし、実行しています）
npx serve -s .output/public
```

ただ、例えば「publicディレクトリの資材をまとめてどこかにアップロードしてちゃんと動作するか確認したい」というケースがあると思います。（むしろ大抵の場合、肝心なのはこっちですよね）

その時に、 index.html はルートディレクトリにhtmlファイルとしてあるので、例えば AWS でいうところの S3 のようなアップロードしたディレクトリ・ファイル構成に従い素直に Web Hosting してくれるサービスだと、「/todoList」などを開こうとしたときに、 404 Not Found になると思います。

これは、 .output/public ディレクトリ配下に出力されたファイル構成を見ての通り、 /todoList のルートに /todoList/index.html や /todoList.html がある訳ではないからです。

### では、上記ケースではどうすれば開けるのか？

Nuxt3 におけるルーティング機能は SSG ビルドの場合、生成されたJavaScript を介して表示すべきものであって、「URLを直接叩いて開く」というSSRのような動作とは異なります。

ですので、「 /todoList 」をJavaScript を介して開きたいのですが、
そのためには /todoList を開く `NuxtLink` を現時点でWebホスティング上から開ける任意のページに配置し、そこからアクセスする必要があります。

現状なら NuxtLink 未使用であり、Webホスティングで開ける唯一のページになっているルートエンドポイント `pages/index.vue` に /todoList へのリンクを書きましょう。

```diff

<template>
  <div>
+   <NuxtLink to="/todoList">ToDoList</NuxtLink>
    <article class="m-4" v-for="post in posts" :key="post.id">
```

リンクを書いたら、改めて `yarn generate` でSSGビルドしてみましょう。

ビルドしたら、`.output/public` ディレクトリ配下を任意のサービスでWeb Hosting させた上で、公開されたルートエンドポイントにアクセスしてみましょう。

すると、追加した `/todoList` 行きの NuxtLink が表示されるはずです。

（ 以降の画像キャプチャは、私が自分の Amazon S3 に `.ouitput/public` ディレクトリ配下をWeb Hosting させてみた際のものです ）

<img width="376" alt="スクリーンショット 2022-07-18 19 08 36" src="https://user-images.githubusercontent.com/41170561/179490074-b329d290-9068-4f46-9278-2678ae7825f3.png">

この状況でリンクを押すと...

<img width="376" alt="スクリーンショット 2022-07-18 19 10 17" src="https://user-images.githubusercontent.com/41170561/179490338-94719058-1ab0-4ad7-ae28-fce6d13bfac7.png">

無事、Web Hosting サービス上で `/todoList` を開けました！

## まとめると

下記でSSGビルド版Nuxt3アプリケーションを開くことができます

1. `nuxt.config.ts` に `ssr: false` を設定
2. `pages/index` に開きたいページのリンクを `NuxtLink` タグで定義する
3. `yarn generate` でSSGビルドを実行
4. `.output/public` 配下を任意のWeb Hosting サービスにアップロード
5. Web Hosting のルートエンドポイントにアクセスし、表示された NuxtLink から開きたいページに遷移する **（JavaScriptが擬似的に生み出しているページなので、 NuxtLink 経由なら開けるが、URLから直接遷移することは不可能 ）**

※ 単なる localhost でのビルド資材動作確認なら、 `npx serve -s "localhostで公開したいディレクトリ"` で動作確認できますが、Web Hosting に実際に載せた場合と異なり、通常のSSRと同様に、NuxtLink 経由なしで直接URL を叩いても目的のページを開けるので、その点に注意が必要ですね

**Comment by gel1123** [comment]
## 余談

私が試しにWeb Hosting してアップロードしたS3 バケットはこんな感じになっています（public ディレクトリ配下をそのままアップロードしたという状況ですね）

<img width="619" alt="スクリーンショット 2022-07-18 19 25 35" src="https://user-images.githubusercontent.com/41170561/179493003-2d53fc9e-2f06-4855-9ba8-5d5264f795d4.png">

上記 S3 バケットのWebホスティングとしての公開URLは下記の通りです。
（参考までに明日 or 明後日頃まで公開しておきますね！　必要であればすぐに消すこともできますので、その時は申し付けください！）

http://azain4645.nuxt3.blog.s3-website-ap-northeast-1.amazonaws.com/

**Comment by azain4645** [comment]
ありがとうございます。

NuxtLinkの設定をしました。（実際はpagesではなくLayoutに記載）
その後、nuxt.config.tsに
ssr: false
を記載したところgenerateが失敗しました。

 ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html]

試しに、ssrの設定を外したところ、generate自体はできたようですが。。

**Comment by azain4645** [comment]
いや、勘違いでした。
ssr:falseを外しても

ERROR  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html]

自体は表示されていました。

**Comment by azain4645** [comment]
とりあえず、
1.nuxt.config.ts に ssr: false を設定
2.pages/index に開きたいページのリンクを NuxtLink タグで定義する
3.yarn generate でSSGビルドを実行
まで出来ました。

凄いですね！200の下にindex.htmlが一つしか存在しないのに驚きました。
これどうなってるんですか？

**Comment by azain4645** [comment]
その後ですが、私もAWSのアカウントを以前作っていましたので、S3に上げてみました！
無事にアップロード公開まで行きましたので、ある程度イメージ沸いて良かったです

http://nuxt3-blog.s3-website.ap-northeast-3.amazonaws.com/

ただ、動作確認してたところ、トップページでは問題ないんですが、post-idのページに行って、画面のリロードすると404になるようです。
調べたところ、動的なリンクを再取得しようとした時に、バケットにそのようなファイルがないので、エラーになるとか、、みたいな記事は見ました。
実際S3で運用は考えていないので、別に構わないといえばそうなんですが、何か知っていましたら教えていただけたら助かります

**Comment by gel1123** [comment]
@azain4645 
おはようございます！　お、azain4645さんの方でも S3 へアップしてみたのですね！
S3は単なるデータ保管庫にしたり、あるいは今回のようにWebホスティングさせることもできたりと、シンプルながら便利なサービスでいいですよね。

> 凄いですね！200の下にindex.htmlが一つしか存在しないのに驚きました。
> これどうなってるんですか？

直感的にはpagesディレクトリ配下の各エンドポイントごとに html が生成されそうなものですけど、そうではなく index.html 一枚しかないのは意外ですよね！

これは、Nuxt.js が SSGビルドで、Nuxtアプリケーションを「単一のエンドポイントからなるアプリケーション」として生成するためこのようになっています！

（擬似的なSPA (single page application) とでも言えばいいですかね...Nuxtは完全なSPAモードのビルドは未対応とのことなのですが、そもそもこう言った話をされてる方がおっしゃる「完全なSPA」の定義を私の方でしっかりと把握していないので、ちょっとここら辺は曖昧な説明になってしまってます！　すみません）

では NuxtLink 経由で todoLink を開いた時には、実際にどのようになっているかというと、その時にはベースとなるhtmlは `index.html` のままで、その代わりに `/_nuxt/todoList-xxxxxx.mjs (xxxxxx はビルド時に割り振られるランダムな文字列)`  が読み込まれることで、 todoLinkページを開けるようになっています！

> ただ、動作確認してたところ、トップページでは問題ないんですが、post-idのページに行って、画面のリロードすると404になるようです。
> 調べたところ、動的なリンクを再取得しようとした時に、バケットにそのようなファイルがないので、エラーになるとか、、みたいな記事は見ました。
> 実際S3で運用は考えていないので、別に構わないといえばそうなんですが、何か知っていましたら教えていただけたら助かります

こちらの疑問点が、ちょうど上記の
「todoLinkページをNuxtLink経由で開くと、index.html から動かないまま、`/_nuxt/todoList-xxxxxx.mjs` が読み込まれる（意訳）」
という話と絡んできます！

あくまで Single Page Application のように、NuxtLink押下時に 対応するページの JavaScript を読み込むことで、開きたいページの情報を index.html 上に展開している状態ですので、

URLから直接 `/post-9` のようなURLに飛ぼうとすると、S3バケット内から「/post-9」というファイルがないかを探す挙動になり、その結果（そんなファイルは存在せず、ただindex.htmlが存在するだけなので） 404 Not Found エラーになるという流れです！（リロードも直接URLを書いて画面を開くのと同じことですからね）

これを解消するには、AWSで例えるなら、アクセスがあったときに、常に index.html と紐づく WebホスティングのルートURLにリダイレクトさせるような機能 を S3 の手前に実装する必要がありますね。（リロードを含むURL直接遷移は全てトップページにリダイレクトさせるという考え方）

具体的には、CloudFront というAWSのCDNサービスを使ってS3に配置したWebホスティングを配信するなら、アクセスがあったときにURLをリダイレクトさせる `Lambda@Edge` を実装するなどのアプローチが考えられますね。

**（ただ、Leambda@Edge 使うならいっそのこと、SSG (Static Site Generater) ではなく、SSR (Server Side Rendering) を使うのがいいかなと思ってます！　そうすればNuxtLinkを経由しない各ページへのアクセス時の404 Not Found も自ずと解消される上に、Nuxt.js が有する強力なバックエンド機能を使えるので）**

**Comment by gel1123** [comment]
@azain4645 
おっと、考えてみたら Amazon S3 の Web Hosting って、リダイレクト機能ありましたね！

これ使えば前述の Lambda@Edge 云々は行わなくとも、S3単品で「常にトップページへリダイレクトさせることで404 Not Found を防ぐ」というアプローチが可能になりますね！

https://dev.classmethod.jp/articles/s3-static-website-hosting-redirect-configuring/

**Comment by gel1123** [comment]
@azain4645 
実際に「S3 Web Hosting で常にトップページへリダイレクトさせる」のをやってみました！

AWSマネジメントコンソールのメニューを
「Amazon S3 > バケット > [バケット名] > 静的ウェブサイトホスティングを編集 」と辿っていくと、編集画面の一番下に「リダイレクトルール」という項目があります。

<img width="681" alt="スクリーンショット 2022-07-19 9 03 03" src="https://user-images.githubusercontent.com/41170561/179636810-58c34039-a03d-4c21-9c83-d3ee08c75621.png">

ここに、下記のルールを設定してやると「404 Not Found なら常にトップページにリダイレクト」させることができるようになります！

```json
[
    {
        "Condition": {
            "HttpErrorCodeReturnedEquals": "404"
        },
        "Redirect": {
            "ReplaceKeyWith": ""
        }
    }
]
```

（リダイレクトルールの公式ドキュメントは [こちら](https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/how-to-page-redirect.html) です！）

※昨日と同様のS3 Web Hosting のエンドポイントに、上記のリダイレクトルール適用してみましたので、もし必要であれば挙動確認に使ってください！

http://azain4645.nuxt3.blog.s3-website-ap-northeast-1.amazonaws.com/

**Comment by gel1123** [comment]
@azain4645 
私自身の覚書も含めたメモです。
どうやら Nuxt3 のバージョンが上がったことにより、 `nuxt generate` の使い勝手が良くなりました！

```diff
   // package.jsonの差分
   "devDependencies": {
     "autoprefixer": "^10.4.7",
-    "nuxt": "3.0.0-rc.4",
+    "nuxt": "3.0.0-rc.6",
     "postcss": "^8.4.14",
     "tailwindcss": "^3.1.6"
   },
```

```bash
# アップデート前
nuxt3-blog % tree .output/public
.output/public
├── 200
│   └── index.html
├── 404
│   └── index.html
├── _nuxt
│   ├── blog-60323b40.mjs
│   ├── counter-9a62ac19.mjs
│   ├── entry-a1a854fe.mjs
│   ├── entry.215a65b2.css
│   ├── fetch-4dd2cee0.mjs
│   ├── fortunePage-5ea41267.mjs
│   ├── index-d5aa6974.mjs
│   ├── manifest.json
│   ├── post-_id_-115ae1fc.mjs
│   └── todoList-66a4ce79.mjs
└── index.html
```

```bash
# アップデート後
nuxt3-blog % tree .output/public
.output/public
├── 200
│   └── index.html
├── 404
│   └── index.html
├── _nuxt
│   ├── blog-466bda46.mjs
│   ├── counter-879e3b02.mjs
│   ├── entry-55d878ee.mjs
│   ├── entry.f726be22.css
│   ├── error-404-18ce5360.mjs
│   ├── error-404.314f7075.css
│   ├── error-500-076ef692.mjs
│   ├── error-500.4e3461e5.css
│   ├── error-component-458b1e0d.mjs
│   ├── fetch-17eb57eb.mjs
│   ├── fortunePage-629a540b.mjs
│   ├── index-fcc91f78.mjs
│   ├── manifest.json
│   ├── post-_id_-9ef73d96.mjs
│   └── todoList-9e0f1f95.mjs
├── counter
│   └── index.html
├── fortunePage
│   └── index.html
├── index.html
└── todoList
    └── index.html

6 directories, 21 files
nuxt3-blog % 
```

ポイントは、下記ですね。

```bash
# アップデート後

├── counter
│   └── index.html
├── fortunePage
│   └── index.html
├── index.html
└── todoList
    └── index.html
```

なんと pagesディレクトリの各ページが、ちゃんと html として出力されるようになりました！
この仕様変更のおかげで、今後は S3静的ホスティングのリダイレクトルールなど設定せずとも問題なく動くようになったはずです！（だいぶ使いやすくなりますね）
